setup.py
this adds package globbing to the setup. it should make the examples work in the installation from egg.
=> add package data globbing

libpysal/api.py
This makes sure that libpysal can still be imported if the user does not have shapely installed.
=> only import the shapely extension if shapely is available

.gitignore, README.rst
It seems that there could be only one main title in README.rst. The format of subtitles like "libpysal modules", "Development" etc. are down-leveled. 
This may help solve the display issues in PyPI. Please compare [libpysal](https://pypi.python.org/pypi/libpysal/3.0.0) vs. [pointpats](https://pypi.python.org/pypi/pointpats/1.0.0)
=> Reformat the README.rst

libpysal/cg/segmentLocator.py
This switches the comparisons to `is` instead of `==`. This avoids failure in the newest numpy, when `_hashKeys` is an array.
=> switch to identity comparisons in segmentLocator

.travis.yml, libpysal/weights/Distance.py, libpysal/weights/tests/test_util.py, libpysal/weights/util.py
I'm quite frustrated I clobbered what looked like quite a bit of work in [pysal/#922](https://github.com/pysal/pysal/pull/922). 
I'm pushing this here because now Github won't let me resurrect my dev branch on pysal proper without just pushing that PR again. 
This fixes [pysal/#944](https://github.com/pysal/pysal/issues/944) by allowing any binary W to be higher-ordered. Also, it enforces that the source weights are binary. 
We need to finish this reorg soon & plug all those tickets up when we can :frowning_face:
=> higher_order typedispatch fix

libpysal/version.py, setup.py
This is bumping the version strings off of the old PySAL versions here. 
I'd like to get a point release of this up on PyPI asap, since the version currently up there has the lag_categorical bug we found in the summer at scipy.
=> bump version for point release of lag cat fix

libpysal/weights/Contiguity.py, libpysal/weights/Distance.py, libpysal/weights/Wsets.py, libpysal/weights/spatial_lag.py, libpysal/weights/spintW.py, libpysal/weights/user.py, libpysal/weights/util.py, libpysal/weights/weights.py
This PR is to update doctests in `weights` module to use `libpysal` instead of `pysal`. Now all the doctests in `weights` module are passed. The [doctest](https://github.com/pysal/libpysal/blob/master/libpysal/weights/Wsets.py#L490) involving the mutual dependence issue #26 is commented for now and would be uncommented once the issue is resolved.
=> update doctests in weights module to use libpysal instead of pysal

libpysal/weights/Wsets.py
This PR is to resolve the circular import issue #26 of `Wsets` and `util`: module `util` import some functions of `Wsets` while `Wsets` needs the function [**WSP2W**](https://github.com/pysal/libpysal/blob/master/libpysal/weights/Wsets.py#L532) defined in `util`. 
In `Wsets`, import **WSP2W** at the top of the module won't work:
```python
from .util import WSP2W
``` 
Placing the import [at the top of function](https://gist.github.com/datagrok/40bf84d5870c41a77dc6) works.
=> resolve circular import in Wsets and util

libpysal/api.py, libpysal/weights/tests/test_util.py, libpysal/weights/util.py
This PR is to add the function ```attach_islands``` which attaches the nearest neighbor to each island of a given pysal/libpysal spatial weight object.
=> add a function to attach the nearest neighbor to island

libpysal/weights/Contiguity.py
This PR to resolve the inconsistency of value data type of dictionary `W.neighbors`.  
[`W.neighbors`](https://github.com/pysal/libpysal/blob/master/libpysal/weights/weights.py#L25) is defined to be a dictionary with region ID as key and **list** of neighbor IDs as **value**. However, in constructing contiguity weights, `W.neighbors` has **set** of neighbor IDs as **value** as shown in #30 . **set** is an unordered data type. Though it is suitable for contiguity spatial weight since all the neighbors have equal weights 1.0 , it is not suitable for others whose neighbors have different weights. To keep consistency, type of **value** of dictionary `W.neighbors` of contiguity spatial weight is forced to be **list** here.
=> change data type of contiguity W.neighbors value from set to list (consistent with other weights)

libpysal/weights/util.py
This PR is to incorporate #32 which made the constructed contiguity weight consistent with the other weights in terms of the data type of dictionary `W.neighbors`'s value (**list** instead of **set**).
=> attach_islands correction: incorporate pr #32

libpysal/weights/weights.py
This adds a plot weights function directly to the W object. 
It takes a geopandas dataframe.
It'll tell you if you don't have matplotlib and so cannot plot. 
It won't tell you if you don't have geopandas, since the function explicitly states that it plots off of a geopandas dataframe as input. 
I haven't written integration testing for this yet, but I'd like to use it in basel, so I figure a point release for an optional/nonstatistical function should be fine.
=> Plot weights

libpysal/weights/tests/test_nx.py, libpysal/weights/weights.py, requirements_plus.txt, setup.cfg
This:
1. removes unnecessary exclude dir from the `setup.cfg`
2. fixes our networkx adapters by making them use sparse machinery round-trip. 
Now, the roundtrip tests pass in `weights/test_nx.py`.
=> fix networkx adapters

libpysal/api.py
this adds the voronoi_frames and voronoiW functions to the api as `voronoi_frames` and `VoronoiW` (faking it to match the same syntax styles as the other class constructors).
=> add voronoi to the API

setup.py
Similar to https://github.com/pysal/giddy/pull/46 to resolve potential encoding issue when reading README.rst to setup the long description
=> force UTF8 encoding for the long description read

libpysal/api.py, libpysal/weights/tests/test_util.py, libpysal/weights/util.py
This implements fuzzy contiguity detection for all features in a GeoDatatFrame. 
It is intended as a complement to #51 which focuses only on fixing island features. This is a more general treatment in that the geometric operations are applied to all features, not just island features.
=> Fuzzy contiguity

libpysal/io/__init__.py, libpysal/io/util/__init__.py, libpysal/io/util/wkb.py, libpysal/weights/__init__.py, libpysal/weights/user.py
This does what we chatted about on gitter.im/pysal/pysal today. 
Please double check that this is consistent over my fork. 
If you'd prefer, please [check it out locally.](https://help.github.com/articles/checking-out-pull-requests-locally/) If your reference to the `pysal/pysal` remote repository is called `upstream`, then you can:
```
git fetch upstream pull/95/head:ljw-imports
git checkout ljw-imports
```
=> Ensure consistency in `from .module import *` in components of libpysal

libpysal/weights/util.py
Resolve https://github.com/pysal/libpysal/issues/94
=> remove function regime_weights

libpysal/cg/kdtree.py, libpysal/weights/distance.py
This makes it so that if `radius` is provided, `distance_metric='arc'` is implied. 
This should ensure the API behaves as expected in #116. 
Currently, you have to pass `distance_metric='Arc'` in order for `radius` to be used. This is because, when we pass a `radius` but keep `distance_metric='euclidean'`, `KDTree` ignores the radius, and returns the `KDTree` according to `distance_metric`
=> Always make spherical KDTrees if radius is passed

CHANGELOG.md, libpysal/__init__.py
This bumps the version (bug fix) for the [draft release](https://github.com/pysal/libpysal/releases/tag/untagged-4e9309ff6881a59aa433).
=> REL: version bump for v4.0.1

libpysal/weights/user.py
this commit fixes the arguments of build_lattice_shapefile for rectangular lattices
=> swapping ncols <-> nrows in the build_lattice_shapefile function

.travis.yml, libpysal/weights/util.py
Bumping  supporting Python versions in TravisCI to match pysal/pysal#1095
{3.5, 3.6} --> {3.6, 3.7}
=> bump supported Python versions and correct lat2SW doctest

libpysal/weights/set_operations.py, libpysal/weights/spintW.py, libpysal/weights/util.py
Many functions do not support `silence_warnings` as mentioned in #134. This PR tries to generically allow `**kwargs` whenever there is a weight constructor underneath a function as proposed by @ljwolf . Even if some functions do support `silence_warnings` now, it is replaced by `**kwargs` for more flexibility. 
Fixes #134
=> Allow for **kwargs any time there's a weights construction

libpysal/weights/weights.py
This resolves #136 by sending the `id_order` down to the new copy of the `W` object. This works in all cases:
1. if `id_order` is not set by the user, then this simply propagates the default (lexsorted) id_order for the dataset, which is now forced to be the same in the new and the old data. 
2. if `id_order` *is* set by user, then this propagates that order exactly.
=> make id_order propagate through symmetrize(inplace=False)

ci/travis/36-latest-conda-forge.yaml, ci/travis/37-latest-conda-forge.yaml
[Background is here.](https://github.com/conda-forge/segregation-feedstock/pull/2)
=> BUG: add zstd as a dependency to work around conda glitch

libpysal/weights/spintW.py, libpysal/weights/weights.py
Addressing #185 
* casting `self.sparse.indices`, `self.sparse.data`, and `self.sparse.indptr` as lists
* adjusting [`docstring`](https://github.com/pysal/libpysal/blob/e6998425b917d342ece7a569abe5df6a15af220a/libpysal/weights/spintW.py#L46-L47) in `weights/spintW.py` to conform to `list` structure
=> Cast arrays as lists (Issue 185) 

libpysal/cg/alpha_shapes.py, libpysal/common.py
This PR moves the import of [`numba.jit`](https://github.com/pysal/libpysal/blob/8c2627f258b5a2ba377f14e80985d8cbcf2b50f1/libpysal/cg/alpha_shapes.py#L11-L25) from `cg.alpha_shapes.py` into `common.py`, which also includes the `HAS_JIT` flag. By switching to this import schema functions within `libpysal` or a federated submodule can benefit from the potential performance improvements (if `numba` is installed).
=> [ENH] moving jit import to common.py / improve documentation

libpysal/weights/weights.py
`silent_island_warning` was removed from the attribute list of `libpysal.weights.W` and was replaced with the name `silence_warnings`, but one occurence was not updated to reflect such change, leading to errors reported in https://github.com/pysal/libpysal/issues/204 and https://github.com/pysal/spreg/pull/27
=> (bug) replace silent_island_warning with silence_warnings for weights

docsrc/Makefile
Currently, we update the contents of [docs/](https://github.com/pysal/libpysal/tree/ed098ea900bde6a9913b96e162d64a72a9615e11/docs) with the built html files in docsrc/_build/html/ (after running `make html`). The existing files in docs/ which do not match those from docsrc/_build/html/ are deleted including  .nojekyll 
This PR is to adjust the makefile to keep .nojekyll in docs/ when syncing between docs/ and docsrc/_build/html/
=> (docs) keep file .nojekyll in docs when syncing between docs/ and docsrc/_build/html/

docsrc/conf.py, requirements_docs.txt
This PR is to update the configuration file for sphinx to:
* automatically generate docstrings for class members including methods, attributes, properties
* avoid display class members twice 
this would be a more convenient fix compared with the solution suggested in https://github.com/pysal/libpysal/pull/209
=> (docs) automatically generate docstrings for class members

libpysal/weights/util.py
Sorry I didn't see #212 earlier. This fixes the described bug by ensuring that the `try/except` block of `libpysal.weights.util.get_points_array()` is safe for lazy input. Before, the [linked explanation succinctly describes the source of the bug.](https://github.com/pysal/libpysal/issues/212#issuecomment-569144720).
=> fix bug 212

CHANGELOG.md, libpysal/examples/__init__.py, libpysal/examples/builtin.py, libpysal/io/iohandlers/csvWrapper.py, libpysal/io/iohandlers/tests/test_csvWrapper.py, libpysal/weights/tests/test__contW_lists.py
This PR addresses:
* pysal/libpysal#214
With the following machine `libpysal` can be read in:
```python
In [1]: %load_ext watermark 
In [2]: %watermark
2019-12-29T19:35:00-05:00
CPython 3.7.5
IPython 7.10.2
compiler   : MSC v.1916 64 bit (AMD64)
system     : Windows
release    : 10
machine    : AMD64
processor  : Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
CPU cores  : 1
interpreter: 64bit
```
**However**, the following errors/failures occur ***in windows*** during local `nosetests` (three of which also occur ***in macOS***[see bottom]):
```
======================================================================
ERROR: test_casting (libpysal.io.iohandlers.tests.test_csvWrapper.test_csvWrapper)
----------------------------------------------------------------------
Traceback (most …
```
=> libpysal 4.2.0 Windows import issue

requirements.txt
This PR addresses the issue raised by @QuLogic [here](https://github.com/pysal/libpysal/pull/176#pullrequestreview-355542455).
* adding full (correct) name for `beautifulsoup4` in `requirements.txt`.
* ~~`bs4`~~ --> `beautifulsoup4`
=> correct name for beautifulsoup4

libpysal/weights/adjtools.py, libpysal/weights/tests/test_adjlist.py
3. [x] This pull introduces new functionality covered by    [docstrings](https://en.wikipedia.org/wiki/Docstring#Python) and [unittests](https://docs.python.org/2/library/unittest.html)? 
4. [N/A] You have [assigned a reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) and added relevant [labels](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/) <- not possible
5. [x] The justification for this …
=> Fix and simplify filter_adjlist.

.coveragerc, .travis.yml, README.rst, requirements_tests.txt, setup.py
This PR makes adjusting following the adoption of `pytest`:
* updates `requirements_tests.py` 
* updates and blackens `setup.py` 
See [good integration practices](http://doc.pytest.org/en/3.0.2/goodpractices.html).
Also adding Python 3.8 to supported versions.
=> Update reqs for tests

.github/workflows/unittests.yml
This PR proposes a complete solution for CI with GitHub Actions based on that of [`spaghetti`'s](https://github.com/pysal/spaghetti/blob/master/.github/workflows/unittests.yml). This workflow allows for the following (from a single `.yml` with a single service):
* tests Ubuntu, Mac, Windows
* tests Python 3.6, 3.7, 3.8
* performs `codecov`
* run nightly tests
* negates dual dependency on Travis and Appveyor for testing
* all tests run concurrently reducing overall time for testing dramatically, especially with Appveyor/Windows tests
Currently, `codecov` is enabled after the unit tests run. In order for this to function properly, someone with admin privileges will have to put the `codecov` token in the Settings/Secrets/ folder. A token is not needed with Travis or Appveyor, but it is …
=> Initializing complete Github Actions CI

ci/36.yaml
This is a minor PR the drops `nose` and a duplicated `codecov` in `ci/36.yml`.
=> dropping nose in ci/36.yml

libpysal/examples/base.py
As #263 states:
> When importing libpysal, the examples are parsed and exported at module import time.
> This means that the example files must be present in all deployments of libpysal,
> which is problematic for us as we're deploying under pyInstaller on a Windows host.
> 
> Furthermore, the usage of __file__ means we cannot simply add the examples to our pyinstaller > spec, as pyinstaller has an odd split of sourcecode files and data files and so the files will not be > where you expect them to be.
This addresses the above by simply making the import of `libpysal.examples` explicit. This passes all tests (I'm erroring on two locally due to missing geopandas, but I expect them to pass on Travis)
There are other ways of resolving this, but this is the simplest and will get discussion …
=> GH-263: Don't implicitly import examples when importing base library

.github/workflows/unittests.yml, README.rst, libpysal/examples/remotes.py
=> Handle connection errors for remote datasets

docs/_sources/index.rst.txt, docs/index.html, docsrc/index.rst
This PR swaps out the Travis CI badge on https://pysal.org/libpysal for the GitHub Actions badge.
=> Docs ci badge

libpysal/weights/tests/test_util.py, libpysal/weights/util.py
Allow specific distance for buffer in `fuzzy_contiguity` instead of a fraction of bbox length. There are cases in which it is better to specify tolerance/buffer as a set known distance instead of a fraction of the df extent. 
I have also change buffering to vectorised operation, so it should be significantly faster, esp. once pygeos will land in GeoPandas.
With this change it could be directly used in https://github.com/pysal/mapclassify/pull/61.
=> ENH: allow specific buffer in fuzzy_contiguity

.github/workflows/unittests.yml
Bump up timeout due to Mac builds seems to take longer. This seems to have solved the issue with `spaghetti` unittests, currently [all 36 are passing](https://github.com/pysal/spaghetti/runs/548801586).
=> Mac builds seem to take longer — bump up timeout

libpysal/cg/ops/_accessors.py, libpysal/cg/voronoi.py, libpysal/common.py, libpysal/examples/__init__.py, libpysal/examples/base.py, libpysal/examples/builtin.py, libpysal/examples/remotes.py
See #290 
This PR adds type hints and standardizes the following docstrings:
* `libpysal/examples/__init__.py`
* `libpysal/examples/base.py`
* `libpysal/examples/builtin.py`
* `libpysal/examples/remotes.py`
=> Standardize libpysal/examples/*.py docstrings

libpysal/io/iohandlers/tests/test_arcgis_dbf.py, libpysal/io/iohandlers/tests/test_arcgis_swm.py, libpysal/io/iohandlers/tests/test_arcgis_txt.py, libpysal/io/iohandlers/tests/test_dat.py, libpysal/io/iohandlers/tests/test_geobugs_txt.py, libpysal/io/iohandlers/tests/test_gwt.py, libpysal/io/iohandlers/tests/test_mat.py, libpysal/io/iohandlers/tests/test_mtx.py, libpysal/io/iohandlers/tests/test_stata_txt.py, libpysal/io/iohandlers/tests/test_wk1.py, libpysal/io/util/tests/test_weight_converter.py
3. [N/A] This pull introduces new functionality covered by [docstrings](https://en.wikipedia.org/wiki/Docstring#Python) and [unittests](https://docs.python.org/2/library/unittest.html)? 
4. [N/A] You have [assigned a reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) and added relevant [labels](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/)
5. [x] The justification for this PR is: 
A filename …
=> TST: Remove unneeded calls to pysal_examples.get_path.

setup.cfg
This PR removes `setup.cfg` as it appears to no longer be used.
=> removing setup.cfg

libpysal/weights/tests/test_util.py, libpysal/weights/util.py
Closes #313 
Implements an option to include lower order contiguities in the result of `higher_order_sp`.
=> ENH: include lower order contiguities in higher_order_sp

libpysal/weights/contiguity.py, libpysal/weights/distance.py, libpysal/weights/tests/test_contiguity.py, libpysal/weights/tests/test_distance.py
`from_dataframe` methods of contiguity and distance weights now defaults to hard-coded `"geometry"` column. This PR uses active geometry column instead. In most of the cases, it will be the same. I encountered this behaviour with gdf with two named geometry columns (none of the called "geometry"). In such a situation it makes sense to default to active geometry.
Some `black` linting also happened  - can remove those if you want.
=> ENH: use active geometry in from_dataframe

.github/workflows/release_and_publish.yml, libpysal/__init__.py
This PR corrects workflow updates in `release_and_publish.yml` and bumps the version to `v4.3.3` for the next iteration of the release to PyPI.
=> Troubleshoot release GHA

libpysal/weights/raster.py, libpysal/weights/weights.py
This pull request adds the `id_order` as a property of the `WSP` class. It is complementary to the work added in [libpysal#343](https://github.com/pysal/libpysal/pull/343).
Background details of raster interface:
1. Earlier, `id_order` was used to map coordinate values (stored in `index` attribute) and the neighbors. It contained the list of indices (basically, `list(range(len(index)))`) in the int format to make the `W` object more memory efficient.
2. After some discussion, we decided to make it more backward compatible with the traditional model used in the libpysal. Therefore, `id_order` now holds the values of the `index` attribute in the form of a list (`index.tolist()`).
3. But after assigning `index.tolist()` to `id_order`, we observed that there was a significant performance loss …
=> [WIP]: id_order as a property of WSP class

README.rst
This PR updates the old "Getting Started" link in `README.rst` (http://pysal.org/getting_started#for-developers) for the link on the most recent iteration of pysal.org (https://pysal.org/docs/devs/).
=> update dev docs link

libpysal/graphs/wxa.py, libpysal/graphs/xarray.py
This xarray-based implementation has `.neighbors`, `.weights`, and `.sparse`. 
Some tricks would be needed to move `.neighbors` from being a method to being indexable, but that's solvable (just need a placeholder class with `__getitem__` iirc
=> xarray geograph implementation

libpysal/graphs/wdf.py, libpysal/graphs/wxa.py
=> Draft of adjacency table as df

libpysal/weights/raster.py
The issue was occurring because of recent changes in `xarray`.  
Relevant threads:
- https://github.com/pydata/xarray/issues/3008
- https://github.com/pydata/xarray/pull/4442
Closes #399
=> Fixed `index2da` causing inverted output

libpysal/io/iohandlers/wk1.py
3. [n/a] This pull introduces new functionality covered by
4. [not possible] You have [assigned a
reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) and added relevant [labels](https://help.github.com/articles/applying-labels-to-issues-and-pull-requ …
=> Add missing endianness in WK1 reader.

.gitattributes
This PR classifies the `libpysal` repo as Python for search search results.
=> classify repo as Python

libpysal/weights/tests/test_util.py
This PR skips `test_lat2SW` for scipy 1.7.1, in addition to 1.7.0. We need to get tests passing again for now, but need to either figure out if we are doing something wrong in [`lat2SW`](https://github.com/pysal/libpysal/blob/master/libpysal/weights/util.py#L1169) or if a bug was introduced into `scipy` in scipy/scipy#14004.
See also:
* #418 (this [comment](https://github.com/pysal/libpysal/issues/419#issuecomment-907535129))
* #419 (this [comment](https://github.com/pysal/libpysal/issues/419#issuecomment-907535129))
* #420
* #423 (this [comment](https://github.com/pysal/libpysal/pull/423#issuecomment-904928037))
=> skip scipy 1.7.1 for in test_lat2SW

libpysal/weights/weights.py
this uses the `toarray` method on a W's sparse matrix format to generate the dense matrix which is much faster than our manual approach
=> use toarray in `W.full()`

libpysal/cg/tests/test_voronoi.py
Floating point results shouldn't be checked exactly, as they might differ on other machines. This test currently fails on at least s390x and aarch64.
=> Fix test_voronoi on other architectures.

libpysal/cg/alpha_shapes.py, libpysal/cg/ops/_accessors.py, libpysal/cg/ops/_shapely.py, libpysal/weights/_contW_lists.py, libpysal/weights/contiguity.py, libpysal/weights/raster.py, libpysal/weights/spatial_lag.py, libpysal/weights/weights.py
Fixes these warnings during build:
```
libpysal-4.5.1.post2/libpysal/weights/contiguity.py:docstring of libpysal.weights.contiguity.Queen.from_xarray:61: WARNING: Enumerated list ends without a blank line; unexpected unindent.
libpysal-4.5.1.post2/libpysal/weights/contiguity.py:docstring of libpysal.weights.contiguity.Rook.from_xarray:61: WARNING: Enumerated list ends without a blank line; unexpected unindent.
libpysal-4.5.1.post2/libpysal/weights/raster.py:docstring of libpysal.weights.raster.da2W:59: WARNING: Enumerated list ends without a blank line; unexpected unindent.
libpysal-4.5.1.post2/libpysal/weights/raster.py:docstring of libpysal.weights.raster.da2WSP:56: WARNING: Enumerated list ends without a blank line; unexpected unindent.
```
and
``` …
```
=> DOC: Fix several warnings during the build

libpysal/examples/base.py
1. [No] Don't have dev environment setup, but tested functionality locally.
5. [Yes] The justification for this PR is: Have been hitting a rare bug here when deploying applications with many worker processes in a Kubernetes environment.  A bit of a race condition exists here where multiple workers attempt to create the directory but fail because another worker already created it, resulting in a crash loop.
=> Bug fix for parallel execution environments

ci/37.yaml, ci/38.yaml, ci/39.yaml, environment.yml, libpysal/weights/util.py, requirements.txt
`LooseVersion` is now deprecated, Python 3.10 warns about that. Using `packaging.version.Version` instead as suggested in the warning.
=> MAINT: replace LooseVersion with packaging

ci/37.yaml, libpysal/cg/alpha_shapes.py, libpysal/cg/tests/test_ashapes.py
Noted by @cornhundred in #456, we've got some surprising behavior for alpha shapes with holes. This attempts to fix this in the `alpha_shape()` function by (1) checking if there are any "holes" in the shapely polygons and, if there are, (2) we only keep polygons that contain an input point. 
This solves the problem OK, but I think there's a bit of an issue: 
Note that this results in two separate polygons-with-holes on the left, but on the right, we retain one of the holes because a point falls within it... I think this happens because the "correct" polygon for that hole would have a zero-area "cut in" that only includes that point. When we use `shapely.ops.polygonize`, we lose that cut in, and thus omit the vertex from the alpha shape. 
Consider this box with a "cut in" from [1,1] to …
=> [WIP] Filter holes from alpha shape returns

.github/workflows/unittests.yml, ci/37-minimal.yaml, libpysal/cg/tests/test_voronoi.py, libpysal/weights/tests/test_contiguity.py, libpysal/weights/tests/test_distance.py, libpysal/weights/tests/test_gabriel.py, libpysal/weights/util.py
Closes #453 
Since this a regression of some sort, I'd recommend issuing 4.6.1 release.
I have also included a CI environment that does not have any optional dependencies so we can catch this issue next time before merging and releasing.
=> revert shapely hard dependecy

libpysal/cg/voronoi.py
This parameter was added in 33b500b but subsequently dropped in b5cde8a without updating the doc comment.
=> Remove non-existant parameter `tolerance` from `voronoi_frames` doc comment

libpysal/cg/locators.py, libpysal/cg/segmentLocator.py, libpysal/cg/shapes.py
This PR follows up from the [2022-05-11 steering council meeting](https://hackmd.io/YCjAJDgOTlKMpcN4H9P2UA?both#Discuss-cg-deprecation) and updates the current warning in [`locators.py`](https://github.com/pysal/libpysal/blob/1766b396cac62ade7f6005acb9efa3c8c584c3fd/libpysal/cg/locators.py#L17) from a `DeprecationWarning`, which is not triggered, to `FutureWarning`. Warnings are also added to all classes in `shape.py` that inherit the [`Geometry` class](https://github.com/pysal/libpysal/blob/1766b396cac62ade7f6005acb9efa3c8c584c3fd/libpysal/cg/shapes.py#L73).
xref #292, pysal/spaghetti#649
=> Update deprecation warnings (shape.py, locators.py)

.coveragerc, libpysal/io/iohandlers/tests/test_db.py, libpysal/weights/adjtools.py, libpysal/weights/spatial_lag.py, libpysal/weights/tests/test_adjlist.py, libpysal/weights/tests/test_util.py
This PR provides solutions for several newish warning cropping up in CI:
* [`fill_diagonal` vs. `insert_diagonal`](https://github.com/pysal/libpysal/actions/runs/3211941490/jobs/5250453173#step:4:1380)
* [`numpy.int` vs. `int`](https://github.com/pysal/libpysal/actions/runs/3211941490/jobs/5250453173#step:4:1339)
* [explicitly use `drop_islands={True, False}` in testing](https://github.com/pysal/libpysal/actions/runs/3211941490/jobs/5250453173#step:4:1307)
* provide a `to_adjlist_kws` keyword argument for functions in [`adjtools.py`](https://github.com/pysal/libpysal/blob/master/libpysal/weights/adjtools.py) to interface with [`W.to_adjlist()`](https://github.com/pysal/libpysal/blob/master/libpysal/weights/weights.py#L275)
* ensure the newHaven dataset is available for testing. this was …
=> Updates warnings, etc.

ci/310.yaml, ci/37-minimal.yaml, ci/37.yaml, ci/38.yaml, ci/39.yaml, libpysal/examples/base.py, libpysal/examples/tests/test_available.py, requirements.txt
`platformdirs` is the [apparent successor]( https://github.com/ActiveState/appdirs/issues/79) to `appdirs`.
This moves to `platformdirs` and adds test coverage.
=> Platformdirs

.github/workflows/unittests.yml, ci/310_shapely20b1.yaml, ci/310_shapely_dev.yaml
This PR tests against `shapely==2.0b1` while excluding `pygeos`
xref https://github.com/pysal/spaghetti/issues/678, https://github.com/pysal/spaghetti/issues/679
=> test against shapely prerelease

examples.ipynb, libpysal/examples/__init__.py, libpysal/examples/base.py, libpysal/examples/builtin.py, libpysal/examples/remotes.py, libpysal/examples/tests/test_available.py, notebooks/examples.ipynb
=> ENH: more granularity in example handling

libpysal/weights/contiguity.py, libpysal/weights/distance.py, libpysal/weights/gabriel.py, libpysal/weights/spintW.py
3. [n/a] This pull introduces new functionality covered by
4. [n/a] You have [assigned a …
=> Fix warnings from Sphinx

libpysal/examples/tests/test_available.py
3. [n/a] This pull introduces new functionality covered by
4. [ ] You have [assigned a
5. …
=> Fix Linux user path test

libpysal/weights/weights.py
We are going to deprecate `id_order` in the future, so the internal use here can be removed to address #507.
=> Removing internal use of id_order in to_adjlist

libpysal/weights/tests/test_adjlist.py, libpysal/weights/weights.py
=> Handle set_index properly in to_adjlist

.github/workflows/unittests.yml, ci/311_shapely_dev.yaml
This adds testing for shapely_dev under 3.11 to help with debugging of:
- https://github.com/pysal/esda/issues/239
- https://github.com/pysal/spopt/issues/346
=> TEST: 3.11 dev coverage

libpysal/weights/tests/test_adjlist.py, libpysal/weights/weights.py
see [my comment in pysal/esda#245](https://github.com/pysal/esda/pull/245#issuecomment-1561815887) for rationale and the fix implemented here.
=> fix indexing issue with adjlist construction

libpysal/weights/tests/test_weights.py
Avoiding the private namespace to fix the CI errors with the latest scipy.
=> TST: fix sparse instance assertion

libpysal/weights/weights.py
Closes #525
We currently do not have any test suite for plotting, so I am not adding any tests here. Will add some as part of the weights refactoring which will include plotting refactoring as well.
=> BUG: fix weights plotting

.github/workflows/unittests.yml, libpysal/graph/tests/test_base.py, libpysal/graph/tests/test_contiguity.py
There are some flaky tests and I suppose that something does not play nice with pytest-xdist, so I disabled it now.
Some linting also happened.
=> TST: fix tests of the Graph class

libpysal/graph/base.py
Clarify `Graph.asymmetry()` docstring.
xref: https://github.com/pysal/libpysal/issues/540, https://github.com/pysal/libpysal/pull/543#issuecomment-1669953445
=> clarify `Graph.asymmetry()` docstring

libpysal/weights/tests/test_weights.py, libpysal/weights/weights.py
=> custom ids for W.asymmetry (#540)

.github/workflows/build_docs.yml, .github/workflows/unittests.yml, ci/311-dev.yaml, libpysal/cg/kdtree.py
Update dev config and fix compatibility with latest scipy which no longer import numpy namespace. (https://github.com/pysal/libpysal/actions/runs/5936839744/job/16098081313)
I also think I have accidentally pushed the first commit straight to main...
=> CI/COMPAT: update CI actions and dev channel setup, fix scipy compatibility 

libpysal/graph/base.py, libpysal/graph/tests/test_base.py
I've noticed that when ids are not ordered, they get ordered within groupby which messes up the conversion to `W`. This seems to fix it.
=> BUG: fix Graph.to_W

libpysal/graph/_kernel.py, libpysal/graph/_triangulation.py, libpysal/graph/base.py, libpysal/graph/tests/test_base.py, libpysal/graph/tests/test_triangulation.py
This is an intermediate step ensuring that all the piping to the constructors works again after it was broken by changes in #548. 
I'll likely self-merge this and continue with the sorting stuff. That may include further changes to data structures returned by individual functions, so don't take the changes here as something we should settle on.
=> fix piping of constructors to Graph after #548

libpysal/graph/_kernel.py, libpysal/graph/_triangulation.py, libpysal/graph/base.py, libpysal/graph/tests/test_base.py, libpysal/graph/tests/test_triangulation.py
This includes proper sorting within triangulation and tests for that.
I believe that we need to sort only by focal and only in cases where the constructor has a tendency to mess up the order. The rest shall always give equal results, so no more sorting shall be needed.
@ljwolf are cliques finished? The implementation does not seem to work, the resulting adjacency is always much shorter than it should be (even shorter than the one before inducing cliques, so something is wrong).
I have also included tests for cliques but since those are failing, they're now marked with xfail. When the implementation is fixed, they should pass (maybe a minor reorder of expected tails will be needed).
@knaaptime on the sorting, I will need to be convinced that we always need to sort by the use case where not …
=> Coindicent tests

libpysal/graph/_utils.py, libpysal/graph/base.py, libpysal/graph/tests/test_builders.py
=> add from_adjacency and handle sorting

libpysal/cg/alpha_shapes.py
A follow-up on #535 trying to eliminate warnings emitted by numba. Locally, this causes no issue, let's see what CI will say.
=> set nopython=True in jit in alpha shapes

libpysal/graph/base.py, libpysal/graph/tests/test_base.py, libpysal/graph/tests/test_builders.py
- removing `get_neighbors` and `get_weights` which are not needed anymore since we have `__getitem__` implemented
- removing `_id2i` as it is unnecessary in sorted adjacency (and we don't need to keep anything in sync, yay!)
- updating indexing to eliminate pandas deprecation warnings
- fixing `from_adjacency` test to pass on windows
=> minor cleanups of geographs

libpysal/graph/_contiguity.py, libpysal/graph/_utils.py, libpysal/graph/base.py, libpysal/graph/tests/test_contiguity.py
I think I already pushed this straight to main... ffs
Anyway, this finalises contiguity stuff on graph.
=> finalise contiguity graph builders

.github/workflows/unittests.yml, libpysal/graph/_kernel.py, libpysal/graph/_triangulation.py, libpysal/graph/_utils.py, libpysal/graph/base.py, libpysal/graph/tests/test_kernel.py
When the kernel function returns zeros, the conversion of sparse to arrays drops observations causing a mismatch in the shape of Graph.sparse and original input.
We simply cannot use `taper`. If there is a good use case for calling `eliminate_zeros()`, we may revise that but with a smarter implementation to avoid this issue. See the test for reproducible example.
=> BUG: fix graph kernel builder when kernel returns zero

libpysal/graph/_contiguity.py, libpysal/graph/_kernel.py, libpysal/graph/_triangulation.py, libpysal/graph/_utils.py, libpysal/graph/base.py, libpysal/graph/tests/test_kernel.py
- `taper` is back and working properly.
- kernel constructors are tested
- fixed issues with conincident points
- exposes sklearn metrics outside knn
One question:
What shall be the behaviour of kernel when `k` is set but the bandwidth s too small so weight is zero, eliminating the link with taper? now the affected focal has less neighbors than K without a warning. I'd say we may warn but that is about it. You can retrieve the rest using `taper=False`.
_edited_
=> finalise kernel constructors in graph 

.github/workflows/unittests.yml, ci/311-dev.yaml, ci/311-no-optional.yaml, libpysal/graph/_triangulation.py, libpysal/graph/tests/test_triangulation.py
Adds more tests of triangulation + a minor change to CI setup to ensure we test code both with and without optional deps, like scikit-learn and numba, while also testing against nightly if sklearn (hence new ci env).
=> triangulation tests + better ci setup

libpysal/graph/_set_ops.py, libpysal/graph/base.py, libpysal/graph/tests/test_base.py, libpysal/graph/tests/test_set_ops.py
The refactor of set operations on Graph based on MultiIndex and inclusion of `to_networkx` to allow `isomorphic` check.
Operations resulting in a combination of edges from two graphs (union, symmetric_difference) are allowed only if their `unique_ids` match, otherwise we do not know the canonical order of adjacency.
I am also excluding isolates from `n_edges` as a self-loop is our internal representation of an isolate and not an edge of a graph.
I have also included all set operations as methods on Graph, following the pandas model.
Tests will come hopefully later today.
=> implement set ops and to_networkx

libpysal/graph/tests/test_set_ops.py
skip when networkx not available to avoid CI failure
=> TST: properly skip isomorphic test

libpysal/graph/_utils.py, libpysal/graph/base.py, libpysal/graph/tests/test_base.py
Clearing up some to-do's in the graph stuff. `higher_order` and components (`n_components`, `component_labels`) stuff is not yet supported in scipy on sparse arrays so going temporarily via sparse matrix.
I also fixed conversion from sparse when islands are present as I bumped into that in `higher_order`.
=> implement higher_order, components via sparse.matrix

.github/workflows/build_docs.yml, .github/workflows/release_and_publish.yml, .pre-commit-config.yaml, docs/conf.py, docs/installation.rst, docs/tutorial.rst
xref: https://github.com/pysal/libpysal/issues/562#issuecomment-1742159791
=> Update release action, etc. to prep for v4.8.0

libpysal/examples/base.py, libpysal/examples/tests/test_available.py
Libpysal will try to create the data directory for storing example data at import time, even if no example objects are used.
We are running a tool in a singularity containers and have libpysal as a subdependency. We do not want to mount the user home directory in the container since this can damage reproducibility (eg python module picked up under `~/.local` etc).
libpysal causes a failure due to "read-only" OSError exceptions when creating the pysal data directory during the import when running in singularity.
This PR simply moves creation of the data dir to the moment when it is actually needed because an example dataset is used.
This avoids the issue we are having mentioned above. Additionaly this also adds a fallback in `get_data_home` to use a temporary directory instead of the users …
=> Delay example data dir creation, add fallback for unwriteable $HOME

libpysal/graph/_set_ops.py
Avoids calling `could_be_isomorphic` with networkx 3.2 due to https://github.com/networkx/networkx/issues/7038
=> avoid could_be_isomorphic on nx 3.2

libpysal/examples/base.py, libpysal/examples/builtin.py, libpysal/examples/remotes.py, libpysal/examples/tests/test_available.py
This PR lints and re-formats the `./examples/*` directory. --> xref #597
=> lint `./examples/*`

libpysal/cg/alpha_shapes.py, libpysal/cg/kdtree.py, libpysal/cg/locators.py, libpysal/cg/polygonQuadTreeStructure.py, libpysal/cg/rtree.py, libpysal/cg/segmentLocator.py, libpysal/cg/shapely_ext.py, libpysal/cg/shapes.py, libpysal/cg/sphere.py, libpysal/cg/standalone.py, libpysal/cg/voronoi.py
xref #589 
This PR formats, lints, & [removes docstring spaces](https://github.com/pysal/libpysal/pull/607#discussion_r1371335093) from `./cg/*.py`. Even though I am trying to do this in coherent sections (left out all `cg` subdirs) some of the PRs are going to be pains to review. I can split into file level PRs if desired.
=> `./cg/*.py` – format, lint, & remove docstring spaces

libpysal/cg/ops/_accessors.py, libpysal/cg/ops/_shapely.py, libpysal/cg/ops/atomic.py, libpysal/cg/ops/tabular.py
This PR formats, lints, & https://github.com/pysal/libpysal/pull/607#discussion_r1371335093 from `./cg/ops/*.py`.
=> format, lint, numpydoc – `cg/ops/*.py`

libpysal/cg/ops/tests/test_accessors.py, libpysal/cg/ops/tests/test_shapely.py, libpysal/cg/ops/tests/test_tabular.py
This PR builds on top of #610 (should review and merge that one first) and formats & lints `cg/ops/tests*.py`
=> format & lint – `cg/ops/tests*.py`

libpysal/graph/base.py
This PR kicks off the linting of `libpysal/graph` with `base.py`.
=> lint `graph/base.py`

libpysal/graph/_contiguity.py, libpysal/graph/_kernel.py, libpysal/graph/_parquet.py, libpysal/graph/_plotting.py, libpysal/graph/_set_ops.py, libpysal/graph/_spatial_lag.py, libpysal/graph/_triangulation.py, libpysal/graph/_utils.py, libpysal/graph/base.py
This PR:
* formats and lints `libpysal/graph/_*.py`
* rename `_set_ops._Set_Mixin` to `_set_ops.SetOpsMixin`
=> lint `graph/_*.py`

libpysal/graph/_utils.py, libpysal/graph/tests/test_builders.py
small tweak, but the existing code will fail when trying to instantiate a kernel graph from a precomputed (sparse) distance matrix (because it has no len)
when passing a precomputed distance matrix its also handy to be able to pass ids as well. I think that would be a small change in this function too, but not sure if we disallowed that for some reason
=> fix index check for precomputed graph distances

pyproject.toml
This should fix the failures on dev that are to be resolved in upstream.
=> TST: ignore pandas dev blockmanager warnings

libpysal/io/fileio.py, libpysal/io/tables.py
This PR formats and lints the top level of `io` --> `libpysal/io/*.py`
@martinfleis My plan for `io` is one PR for each subdir (4 + this one) unless you want me to tack anything else on here.
* `geotable/*`
* `iohandlers/*`
* `tests/*`
* `util/*`
=> lint & format `io/*.py`

libpysal/io/geotable/dbf.py, libpysal/io/geotable/file.py, libpysal/io/geotable/shp.py, libpysal/io/geotable/tests/test_utils.py, libpysal/io/geotable/utils.py, libpysal/io/geotable/wrappers.py
This PR formats and lints `libpysal/io/geotable/*`
=> lint & format – `io/geotable/*`

libpysal/graph/_plotting.py, libpysal/graph/base.py, libpysal/graph/tests/test_plotting.py
Follow-up on #617
We were not able to change anything about the map as we forgot to pass kwargs though like we did in `esda`. But stuff like `tiles`  or `prefer_canvas` shall work out of the box.
=> pass kwargs to explore

ci/310-oldest.yaml, ci/310.yaml, ci/311.yaml, ci/312-dev.yaml, ci/312-no-optional.yaml, ci/312.yaml, environment.yml, libpysal/weights/tests/test_contiguity.py, pyproject.toml
This PR removes `xarray` as hard dependency, which is causing [feedstock failures](https://github.com/conda-forge/libpysal-feedstock/pull/22)
* xref – https://github.com/pysal/libpysal/pull/585#issuecomment-1793482193
* xref – https://github.com/conda-forge/libpysal-feedstock/pull/22#issuecomment-1793339557
=> remove `xarray` as hard dependency

.github/workflows/unittests.yml
Closes #606 
The issue comes from pooch. Multiple workers are trying to download the archive at the same time, corrupting the file in the process. Or second worker is trying to read partially downloaded archive that the first one is still writing. We do avoid this with libpysal.examples by fetching them ahead of the time. We can do the same with geodatasets.
=> GHA: allow multi-core testing again

libpysal/io/iohandlers/arcgis_dbf.py, libpysal/io/iohandlers/arcgis_swm.py, libpysal/io/iohandlers/arcgis_txt.py, libpysal/io/iohandlers/csvWrapper.py, libpysal/io/iohandlers/dat.py, libpysal/io/iohandlers/db.py
This PR
* breaks out #630 (part 1 of $n$)
* formats and lints `io/iohandlers{a-d}.py`
=> lint & format `io/iohandlers{a-d}.py`

libpysal/io/iohandlers/gal.py, libpysal/io/iohandlers/geobugs_txt.py, libpysal/io/iohandlers/geoda_txt.py, libpysal/io/iohandlers/gwt.py, libpysal/io/iohandlers/mat.py, libpysal/io/iohandlers/mtx.py
This PR:
* breaks out https://github.com/pysal/libpysal/pull/630 (part 2 of $n$)
* formats and lints `io/iohandlers{g-m}.py`
=> lint & format `io/iohandlers{g-m}`.py

libpysal/io/iohandlers/pyDbfIO.py, libpysal/io/iohandlers/pyShpIO.py, libpysal/io/iohandlers/stata_txt.py
This PR:
* breaks out https://github.com/pysal/libpysal/pull/630 (part 3 of $n$)
* formats and lints `io/iohandlers{p-s}.py`
=> lint & format `io/iohandlers{p-s}.py`

libpysal/io/iohandlers/tests/test_arcgis_dbf.py, libpysal/io/iohandlers/tests/test_arcgis_swm.py, libpysal/io/iohandlers/tests/test_arcgis_txt.py, libpysal/io/iohandlers/tests/test_csvWrapper.py, libpysal/io/iohandlers/tests/test_dat.py, libpysal/io/iohandlers/tests/test_db.py, libpysal/io/iohandlers/tests/test_gal.py, libpysal/io/iohandlers/tests/test_geobugs_txt.py, libpysal/io/iohandlers/tests/test_geoda_txt.py, libpysal/io/iohandlers/tests/test_gwt.py, libpysal/io/iohandlers/tests/test_mat.py, libpysal/io/iohandlers/tests/test_mtx.py, libpysal/io/iohandlers/tests/test_pyDbfIO.py, libpysal/io/iohandlers/tests/test_pyShpIO.py, libpysal/io/iohandlers/tests/test_stata_txt.py, libpysal/io/iohandlers/tests/test_wk1.py, libpysal/io/iohandlers/tests/test_wkt.py
This PR:
* breaks out https://github.com/pysal/libpysal/pull/630 (part 5 of $n$)
* formats and lints `io/iohandlers/tests/*.py`
=> lint & format `io/iohandlers/tests/*.py`

libpysal/io/tests/test_FileIO.py, libpysal/io/tests/test_Tables.py, libpysal/io/util/wkb.py, libpysal/io/util/wkt.py
This PR formats and lints `io/{tests, util}/*.py` –  part 1 of $n$
=> lint & format `io/{tests, util}/*.py` part 1

libpysal/io/util/shapefile.py
This PR:
* formats and lints `io/{tests, util}/*.py` –  part 3 of 3 
* wraps up `io/`
=> lint & format `io/{tests, util}/*.py` part 3

libpysal/weights/_contW_lists.py, libpysal/weights/adjtools.py
This PR:
* formats and lints `weights/*.py` –  part 1 of $n$
=> lint & format `weights/*.py part 1

libpysal/weights/weights.py
This PR:
* formats and lints `weights/*.py` –  part 6 of $n$
=> lint & format `weights/*.py` part 6

libpysal/weights/tests/test_Wsets.py, libpysal/weights/tests/test_user.py, libpysal/weights/tests/test_util.py, libpysal/weights/tests/test_weights.py, libpysal/weights/tests/test_weights_IO.py, libpysal/weights/weights.py
This PR:
* formats and lints `weights/*.py` –  and should be part 8 of 8
* nearly completes the linting of `libpysal` -> there seem to be some loose ends in `cg` that I will take care of in a follow PR.
=> lint & format `weights/*.py` part 8

libpysal/graph/_utils.py, libpysal/graph/base.py, libpysal/graph/tests/test_base.py
I have found myself in a need to create subsets of a large graph covering only specific portions of my geometries. Hence I have developed a method to create a subgraph since making a subset of adjacency and passing that to a constructor discards isolates.
=> ENH: add subgraph method to Graph to get subsets

libpysal/graph/_set_ops.py, libpysal/graph/base.py
Closes #632 
When we know that the adjacency series is sorted as it is supposed to, we can skip sorting in `__init__`. This is particularly noticeable with large graphs of tens of millions edges. 
There may be some cases that we know are sorted and could use this. I thought that everything that goes through `_resolve_islands` is sorted but if I pass `is_sorted=True` everywhere, I get some strange failures. So better be safe than sorry in this case. Sorting is sensitive here.
=> fast-path for initialisation of Graph for adjacency that is known to be sorted

libpysal/graph/base.py, libpysal/graph/tests/test_base.py
=> ENH: Graph.eliminate_zeros, refactor isolates

.pre-commit-config.yaml, libpysal/cg/standalone.py, libpysal/graph/_kernel.py, libpysal/io/fileio.py, pyproject.toml
This PR:
* cleans up several lingering formatting & linting spots
* updates `.pre-commit` for for `black` and `ruff`
* xref #589
To decide:
* Within `pyproject.toml`, I am more leaning towards the mindset of omitting [`[tool.ruff.ignore]`](https://github.com/pysal/libpysal/blob/9e459608ef1b34e41ef63711da8e86c5ca085f7c/pyproject.toml#L89) in `pyproject.toml` altogether and handling 99.9% of cases within files themselves (everything in the PR passes that way). However, I know others may think this is too strict. So yay or nay for keeping `[tool.ruff.ignore]`?
Once the PR is reviewed and merged the last step in #589 will be to [enable `pre-commit` on triggered GHA](https://results.pre-commit.ci)
=> final lint/format run through & update pre-commit

.github/CONTRIBUTING.md, .pre-commit-config.yaml, docs/installation.rst, libpysal/cg/standalone.py, libpysal/graph/tests/test_contiguity.py, pyproject.toml
This PR:
* follows the example in [`xarray-contrib/xvec`](https://github.com/xarray-contrib/xvec/pull/54/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R7) for swapping out `black` for `ruff format` in formatting
* updates `pyproject.toml` of this
* makes several minor linting and formatting corrections
* updates contributing guidelines and `docs/install` for supported Python versions 
xref #589
=> Formatting via `ruff`

libpysal/graph/base.py, libpysal/graph/tests/test_base.py
Closes #668
@knaaptime this includes pandas-fu version as well as roundtrip via sparse for now. Timing below. 
```py
import geopandas as gpd
from geodatasets import get_path
from libpysal import graph
df = gpd.read_file(get_path("geoda.ncovr"))
contig  = graph.Graph.build_contiguity(df)
%%timeit
contig.fill_diagonal()
5.31 ms ± 108 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
%%timeit
contig.fill_diagonal_sparse()
16.3 ms ± 92.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
Here, the sparse version is about 3x slower. This ratio seems to be more or less consistent with any size of the graph.
=> ENH: include assign_self_weight (formerly fill_diagonal) in Graph

.github/workflows/unittests.yml, libpysal/graph/tests/test_utils.py
GeoDa Columbus was removed from geodatasets as it has incorrect CRS information, so we can't use it anymore. This should fix the failing CI.
=> TST: avoid using GeoDa Columbus from geodatasets

libpysal/graph/base.py, libpysal/graph/tests/test_base.py
=> ENH: add Graph.apply, Graph.aggregate and allow callable as transformation in transform

.github/workflows/reverse.yml
This is very much WIP because to make this work we need to ensure that the state of CI in downstream PySAL packages is as it should be. 
Once this works, it ensures that libpysal release does not break anything in the rest of the federation (xref #631). I'll see if there's some more work needed on the side of the action (I created the beta version during the Scientific Python summit, so have admin rights over it). But it will likely require changes in downstream (e.g. you can see that `tobler` does not properly skip H3 tests etc.).
The trigger is temporary to make sure we can properly test it here. We can then discuss when this should run but it should run before any release for sure and in the optimal situation should be required to pass for a release.
=> GHA: include reverse dependency testing

libpysal/graph/_matching.py, libpysal/graph/base.py
Somehow #666 did not include a docstring of the public method, only of the private one, which was incorrectly formatted. Fixing both cases.
=> DOC: include docstring in matching

.github/workflows/reverse.yml
Remove parallel execution to resolve those `quilt3` issues, add some missing dependencies.
Couldn't make opencv work but we should resolve that in pointpats by a) skipping the test then cv2 cannot be imported, b) refactoring the minimum_bounding_rectangle on top of shapely instead.
See the log of the latest run with this config [here](https://github.com/martinfleis/libpysal/actions/runs/7703159298)
mgwr, pointpats, spvcm, tobler remain failing, all of which need to be solved in upstream.
xref #681
=> CI: partially resolve reverse dep testing issues

libpysal/graph/base.py
pandas no longer returns names of MultiIndex as a list but as a tuple. Making our check compatible.
This will need to be released before pandas 3 which is scheduled for April. Otherwise, graph module will be unusable with pandas 3.
=> COMPAT: compatibility with pandas 3

libpysal/graph/base.py
Closes #672 
For adjacency of 1,404,080 edges, the conversion time is 42.7s on main and 4.5s in this PR.
@jGaboardi not sure how to properly label this...
=> REF: refactor Graph.to_W to avoid perf bottleneck

libpysal/cg/voronoi.py
While using the new `voronoi_frames` on a fairly large dataset, I noticed this issue libgeos/geos#1062 plus another where some polygons coming from GEOS were not actually valid, likely due to the same reason. This is a workaround that solves all I faced.
=> Work around GEOS issue in voronoi_frames

libpysal/graph/base.py
Closes #687 
See https://github.com/pysal/libpysal/issues/687#issuecomment-1969926764
=> DOC: clarify the requirements of the canonical sorting of Graph index

libpysal/graph/base.py
Starting the work on the Graph documentation.
=> DOC: add example to Graph.to_W

libpysal/graph/base.py
Add docstring examples to build_distance_band
=> DOC: Add examples to build_distance_band

libpysal/graph/base.py
Add docstring examples to build_contiguity and build_triangulation
=> DOC: add examples to build_contiguity and build_triangulation

libpysal/graph/_spatial_lag.py, libpysal/graph/base.py, libpysal/graph/tests/test_base.py
Follow up on #691 and conversion to `neighbors` and `weights` dicts as discussed there.
I am also changing the sparse format to CSR which is what we need for lag and generally anything else and what weights is using. That also allows cleaner implementation of `_components`.
Plus using `matrix_power` implementation for scipy sparse array (courtesy of @ljwolf) which allows us to skip conversion to sparse matrix.
Note that the change of the sparse representation is technically a hard-breaking change but given we're in experimental phase we can afford it.
=> REF: minor performance improvements in Graph

ci/312-dev.yaml, ci/312.yaml
This PR adds back `numba` into the Python 3.12 tests.
* resolves https://github.com/pysal/libpysal/issues/590
* xref
* https://github.com/pysal/libpysal/pull/585
*  https://github.com/numba/numba/issues/9197#issuecomment-1923489918
=> add back `numba` in Py312 tests

libpysal/graph/_triangulation.py, libpysal/graph/tests/test_builders.py
Found a bug in Gabriel graph. heads and tails come unsorted from filtering, resulting in misaligned weights. See repr:
```py
import geopandas
from libpysal.graph import Graph
import momepy
blgs = geopandas.read_file(momepy.datasets.get_path('bubenec'), layer='buildings')
delaunay = Graph.build_triangulation(blgs.centroid, "delaunay", kernel="identity")
gabriel = Graph.build_triangulation(blgs.centroid, "gabriel", kernel="identity")
relative = Graph.build_triangulation(blgs.centroid, "relative_neighborhood", kernel="identity")
>>> delaunay[48]
neighbor
46      24.357863
47      32.418353
49      49.764015
74     155.698588
75      99.914953
141     93.302955
Name: weight, dtype: float64
>>> gabriel[48]
neighbor
46    128.634198
47     24.117386
Name: weight, dtype: float64
>>> relative[48] …
```
=> BUG: misaligned weights in the gabriel graph

libpysal/graph/_kernel.py, libpysal/graph/_triangulation.py, libpysal/graph/_utils.py
I was building some triangulation graphs on a fairly large data (150k points)  and it took 25 minutes. I figured that vast majority of time was consumed by the handing of coincident points, even though there were no coincident points in the whole dataset. With this PR, the same Gabriel graph took 7s.
See the timings on a repr:
```py
coords = np.random.rand(10000, 2)
g = Graph.build_triangulation(coords, kernel="identity")
```
The tests on this will fail until #709 is merged.
=> PERF: don't build coincident lookup if not needed

libpysal/graph/_kernel.py, libpysal/graph/_triangulation.py, libpysal/graph/_utils.py, libpysal/graph/base.py, libpysal/graph/tests/test_builders.py, libpysal/graph/tests/test_kernel.py, libpysal/graph/tests/test_triangulation.py
Closes #713 
Had to touch more stuff than intended but we now rely on QHull to identify coincident points and provide a lookup from which we can build cliques. This should ensure that we won't hit the precision issues. 
Some minor cleanup happened alongside, i.e. to avoid solving isolates twice in a row.
=> Refactor handling of coincident points in triangulation

libpysal/graph/_utils.py, libpysal/graph/base.py
I've done some profiling which led to these changes.
- avoiding re-creation of adjacency and re-sorting already sorting arrays in `_sparse_to_arrays` - cuts time to about half
- faster `_reorder_adjtable_by_ids` (no apply) (10x faster than original)
- `_validate_sparse_input` is removed as it is not used anywhere
We still do sorting multiple times in many places but if I short-circuit that, we hit #687 and issues with sparse round tripping. The final sorting either needs to happen in `__init__` as now or would need to happen in `.sparse`. Keeping it in the constructor is probably better idea as we know that a Graph is always correct as is.
=> PERF: sorting-related improvements in Graph

libpysal/graph/_utils.py, libpysal/graph/base.py, libpysal/graph/tests/test_base.py
This PR adds a method to the graph api which takes an array of values and calculates descriptive statistics within each neighborhood. 
Optionally, some neighbors can be filtered out based on the percentiles of the passed values.
The supported stats are - "count", "mean", "median", "std", "min", "max", "sum", "nunique" and "mode".
The method similar to .apply, but all values are calculated in one grouping operation and all functions are jitted.
=> ENH: include Graph.describe() to describe neighbourhood values

libpysal/graph/_spatial_lag.py, libpysal/graph/base.py, libpysal/graph/tests/test_spatial_lag.py
This has two changes from the creation of categorical spatial lags using W
1. `categorical` is now an option in `_lag_spatial`, to unify treatment of the lag.
2. This will raise an exception in the case where `categorical=True` , `ties=raise`, and ties are encountered.
"Explicit is better than implicit."
=> Categorical spatial lag using the Graph

libpysal/graph/base.py
We don't use types anywhere in the module and these were also using deprecated numpy dtype. Removing for consistency.
Fixes https://github.com/pysal/mapclassify/issues/214
=> COMPAT: remove typing from Graph.describe

libpysal/examples/remotes.py
=> Add timeout in request to handle off-line use cases in examples

libpysal/graph/_contiguity.py, libpysal/graph/base.py, libpysal/graph/tests/test_builders.py, libpysal/graph/tests/test_contiguity.py
When using `fuzzy_contiguity` with a buffer, it may be worth using a lower resolution to speed up the computation. This enables passing kwargs to buffer to allow this type of control.
=> ENH: pass kwargs to buffer in fuzzy_contiguity

ci/312-dev.yaml, libpysal/cg/voronoi.py, libpysal/examples/remotes.py
Closes #722 
The issue probably won't pop-up for users given it is in the legacy implementation you would need to import directly.
Also adding numpy nightly to dev env.
=> COMPAT: fix numpy 2.0 incompatibility

libpysal/graph/_utils.py, libpysal/graph/tests/test_triangulation.py
Fixes #724
In the end, the results were just in a slightly different order but (head, tail, weight) tuple was always correct. Given we do sorting ourselves in the constructor anyway, this has no impact on creation of graph. Just an intermediate arrays are in different order. Canonically sorting the output before assertion solves the issue.
If you build the full Graph using `build_triangulation`, they are identical.
=> COMPAT: ensure argsort output has a stable order in numpy 2

ci/312.yaml, pyproject.toml
3. [n/a] This pull introduces new functionality covered by
4. [n/a] You have [assigned a …
=> DOC: Remove unused mkdocs-jupyter dependency

libpysal/graph/base.py, libpysal/weights/contiguity.py
3. [x] This pull introduces new functionality covered by
4. [n/a] You have [assigned a
5. …
=> DOC: Fix a couple Sphinx warnings

.github/workflows/reverse.yml
Minor update of the reverse dep testing. I'd like to get it green soon-ish.
=> CI: ignore spvcm, add osmnx to env, xfail stuff out of control in reverse dep testing

libpysal/common.py
3. [x] This pull introduces new functionality covered by
4. [n/a] You have [assigned a
5. …
=> Use importlib to implement simport

.github/workflows/reverse.yml
with 0.7.2 released earlier today, momepy should not fail any longer. Will need a merge to trigger.
=> CI: do not xfail momepy in reverse checks

libpysal/graph/base.py, libpysal/graph/tests/test_base.py
Work over in esda uncovered a series of bugs related to handling of self-weights with 0 weight which are **not** isolates at the same time. I hope that this fixes them all. They are all tested, either in their own or in related tests. Reverting each would cause CI to fail.
This is precisely the reason why I started doing the support of Graph in esda, in hope that it verifies that Graph works as intended.
This is required for https://github.com/pysal/esda/pull/293/ to pass, alongside #742.
=> BUG: fix handling of non-isolate self-weights of 0 and order preservation

libpysal/graph/_spatial_lag.py, libpysal/graph/tests/test_spatial_lag.py
While doing #745 we have noticed that categorical lag works only for graphs based on default range index.
This fixes it.
=> BUG: fix categorical lag for custom index

libpysal/graph/base.py, libpysal/graph/tests/test_base.py, libpysal/weights/util.py
Fixes #738 
Funnily enough, we have the same line of code in `weights/raster.py`, where it is correct.
=> fix higher_order contiguity including lower order

libpysal/graph/_summary.py, libpysal/graph/base.py, libpysal/graph/tests/test_summary.py
For non-binary weights, asymmetry check can be pretty costly. If we compute that by default in `summary`, it comes with a massive overhead when we need just s0, s1, s2 in esda. Adding a keyword that disables it by default. That way the overhead of computing stuff we don't need in esda is relatively negligible (still some but that is probably okay).
=> make asymmetry computation in Graph summary optional

docs/api.rst
I am still not sure if this is not premature given the number of bugs I've found while doing the Graph support in esda but here it is. Once this is merged, `Graph` is considered stable.
=> DOC: move Graph from experimental to stable API

ci/310-latest.yaml, ci/310-oldest.yaml, ci/311-latest.yaml, ci/312-dev.yaml, ci/312-latest.yaml, libpysal/graph/__init__.py, libpysal/graph/_network.py, libpysal/graph/base.py, libpysal/graph/tests/test_builders.py
```python
import geodatasets
import geopandas as gpd
from geosnap import io
from libpysal.graph import Graph
df = gpd.read_file(geodatasets.get_path("geoda cincinnati"))
net = io.get_network_from_gdf(df)
Graph.build_travel_distance(df.set_index('ID'), net, 500, kernel=None).adjacency
>>> focal     neighbor
726907.0  726907.0      0.000000
709415.0    385.609009
709472.0    309.471985
738259.0    346.858002
738277.0    247.363007
...    
703708.0  703537.0    349.321014
703574.0    190.669006
703629.0    370.070007
703686.0    447.006989
703708.0      0.000000
Name: weight, Length: 8075, dtype: float64
Graph.build_travel_distance(df.set_index('ID'), net, 500, kernel='triangular').adjacency
>>> focal     neighbor
726907.0  726907.0    1.000000
709415.0    0.228782
709472.0    0.381056 …
```
=> add graph from travel network

libpysal/graph/base.py, libpysal/graph/tests/test_base.py
This PR fixes #759 .
Pandas aggregation functions pass the original string index to numba, and thats why it fails the type check.
To fix this we can either have two new numba mode calculation functions - one for  strings, one for numbers or we can explicitly recast the index to integers, carry out the calculations using the numeric index and then reindex the results before returning them.
=> Fix for Graph.describe() when the graph has a string index (#759)

libpysal/weights/spatial_lag.py
Ensures that when downstream packages (like splot https://github.com/pysal/splot/pull/184) use `lag_spatial` when a Graph is given, the actual computation produces correct lag. This will avoid silent introduction of bugs when using Graph as scipy does not raise but produces different output.
=> ENH: ensure lag_spatial is compatible with both W and Graph

ci/310-oldest.yaml, libpysal/graph/_indices.py
Requires https://github.com/pysal/tobler/pull/218 to work, so likely only dev and oldest will pass until Tobler gets a patch release.
=> COMPAT: h3 v4 compatibility

libpysal/cg/voronoi.py
On some of the locations where `coverage_union` failed, unary union does not fail but produces invalid polygons. If that happens, the subsequent intersection has a tendency to fail. This seems to fix it but I wasn't able to extract a sample small enough to be included in CI. So my proposal is not merge as is.
=> BUG: ensure validity of polygons in voronoi_frames

libpysal/cg/voronoi.py
should fix the CI failure on oldest.
=> COMPAT: fix backwards compatibility with old geopandas

libpysal/weights/gabriel.py, libpysal/weights/tests/test_gabriel.py
This PR fixes #801:
* Fix the Toussaint RNG-2 condition: prune $(i,j)$ if ∃ $k$: $\max(d_{ik}, d_{jk}) < d_{ij}$
* include last node: `n = len(coordinates)` and skip `k == i or k == j`
* Updated the test (the resulted graph in shown below)
=> BUG: RNG pruning condition and loop bound
