libpysal/__init__.py, libpysal/cg/ops/_shapely.py, libpysal/cg/ops/tests/test_tabular.py, libpysal/common.py, libpysal/io/Tables.py
1. [X] You have run tests on this submission, either by using [Travis Continuous Integration testing](https://github.com/pysal/pysal/wiki/GitHub-Standard-Operating-Procedures#automated-testing-w-travis-ci) testing or running `nosetests` on your changes?
2. [X] This pull request is directed to the `pysal/dev` branch.
3. [X] This pull introduces new functionality covered by
4. [X] You have [assigned a
reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests-to- …
=> Fix testing for pandas optional imports 

README.rst, libpysal/__init__.py
=> Fix for #7

libpysal/io/util/shapefile.py
This ports @hasecbinusr's PR, #934 to libpysal.
=> merge pysal/#934 by @hasecbinusr to libpysal

libpysal/weights/adjtools.py, libpysal/weights/tests/test_adjlist.py, libpysal/weights/tests/test_nx.py, libpysal/weights/util.py, libpysal/weights/weights.py
Hey, I **finally** got this stuff ready to go. It was finishing the unittests and [making a clean example notebook](https://gist.github.com/ljwolf/6673b2bc7b5a45e3b6183c4240037b16) that took the longest. Always hardest to get the thread through the eye than to find the kit, I guess. 
I'd recommend checking out the notebook to see what's enabled by these tools, as well as what I plan on building up.
=> adjacency list tooling (prep for wombling/disparity analysis module)

libpysal/weights/Distance.py, libpysal/weights/tests/test_Distance.py
This pulls in the three line changes needed to adresss bug [pysal#945](https://github.com/pysal/pysal/issues/945). I'd rather see this merged here than elsewhere. 
Still needs unittesting.
=> pass ids through to _distance_to_W

libpysal/weights/spatial_lag.py, libpysal/weights/tests/test_spatial_lag.py
this replicates [pysal#950](https://github.com/pysal/pysal/pull/950/files).
=> fix bug with integer lag categorical class

libpysal/version.py
this bumps the stable release date in the version.py file.
=> bump stable date

libpysal/weights/tests/test_Wsets.py
There does not exit a unit test for function `w_clip`. This PR is to add the unit test.
=> add unittest for Wset.w_clip

libpysal/weights/spatial_lag.py
This fixes an induced bug in the `lag_categorical`code and tries to make the names in `lag_categorical` more intuitive/meaningful for maintainers. Also, it adds a docstring to the internal `_resolve_ties` function.
=> fix id2i lookup for string names and make better names

libpysal/weights/_contW_lists.py
This is the stub for the linestring network.
=> [WIP]: add linestring/multilinestring functionality

libpysal/weights/_contW_lists.py, libpysal/weights/tests/test_Contiguity.py
There were a few things I was commenting on in a self-review that needed to be fixed before merging #61. 
This addresses that self-review.
=> Remaining concerns left unfixed in #61

libpysal/weights/util.py
=> changed geometry column name from a str to an attribute

libpysal/weights/weights.py
=> only warn once for islands/disconnected components

libpysal/weights/util.py
resolves #63
do  we need to test for this case as well?
=> check for spatial index if nonplanar neighbors

libpysal/weights/tests/test_weights_IO.py
=> fix hardcoded swm test

libpysal/cg/__init__.py
=> including rtree in imports

libpysal/cg/__init__.py, libpysal/cg/alpha_shapes.py, libpysal/io/__init__.py, libpysal/weights/__init__.py
this ensures consistency around using `__all__`, and removes the `del` statements.
=> remove `del` statements and modify alphashape __all__

README.rst, libpysal/__init__.py, libpysal/examples/__init__.py, libpysal/examples/_version.py, libpysal/version.py, setup.py
* Change `version` to ` __version__`
* Delete version.py in example folder 
* Update README.rst - DELETE instruction on `import libpysal.api` since there is not an `api.py`
=> version name as __version__

libpysal/weights/weights.py
=> docstrings for attributes are defined in properties

.travis.yml, requirements_plus.txt
follow up with #106 
When `"$PYSAL_PLUS" == true`, tests get run:
=> Add dependencies to requirements_plus.txt for test_db

requirements_doc.txt
=> doc: requirements

libpysal/cg/alpha_shapes.py, libpysal/cg/tests/test_ashapes.py
this addresses #111.
My testing stack is broken at the moment, so I'm relying on travis for unittests. 
Will tag a reviewer once/if they pass.
=> [WIP] ensure safe returns for small n alphashapes

libpysal/weights/util.py
=> BUG: fix for scipy bump #154

setup.py
related to https://github.com/pysal/libpysal/pull/154/files "bump supported Python versions to python 3.6 and 3.8"
=> update setup.py to accommodate the transition to python3.6 and 3.7

.travis.yml
=> removing alumni devs from travis notifications  (#161)

libpysal/cg/alpha_shapes.py, libpysal/cg/tests/test_ashapes.py, libpysal/weights/adjtools.py, libpysal/weights/tests/test_adjlist.py
1. [X] You have run tests on this submission, either by using [Travis Continuous Integration testing](https://github.com/pysal/pysal/wiki/GitHub-Standard-Operating-Procedures#automated-testing-w-travis-ci) testing or running `nosetests` on your changes?
2. [X] This pull request is directed to the `pysal/master` branch.
3. [X] This pull introduces new functionality covered by
4. [X] You have [assigned a
reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests- …
=> swap to masking instead of querying in adjlist

.travis.yml, CHANGELOG.md, ci/travis/36-latest-conda-forge.yaml, ci/travis/37-latest-conda-forge.yaml
1. [X] You have run tests on this submission, either by using [Travis Continuous Integration testing](https://github.com/pysal/pysal/wiki/GitHub-Standard-Operating-Procedures#automated-testing-w-travis-ci) testing or running `nosetests` on your changes?
2. [X] This pull request is directed to the `pysal/master` branch.
3. [ ] This pull introduces new functionality covered by
4. [X] You have [assigned a
reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests- …
=> Modernize the travis builds

libpysal/weights/weights.py
This PR is to fix the doc typos for silence_warnings of pysal.lib.weights.W (https://github.com/pysal/pysal/issues/1098) as well as to optimize the warning message output. 
The logic is that: 
* first check whether there are disconnected components:
* if yes
* print the number of disconnected components
* then check if there are islands
* if yes
* print the number of islands along with islands ids.
* if no
* not print messages about islands
* if no
* no warning messages
=> (docs, bug) silence warning for disconnected components and islands

ci/travis/36-latest-conda-forge.yaml, ci/travis/37-latest-conda-forge.yaml, libpysal/cg/voronoi.py, libpysal/weights/contiguity.py, libpysal/weights/tests/test_contiguity.py, libpysal/weights/tests/test_user.py, libpysal/weights/weights.py
This is some very dank code smell, so there may be a better way of doing this. But, I wanted there to be a `from_dataframe` constructor for the `Voronoi` function. We made this function `Voronoi` look like a class, but it will output either a `Rook` or a `Queen` instance depending on the criterion requested. But, we wanted this "function" to look like a class, since all our other constructors are classes. So, we gave the `Voronoi` function an upper case name, to make it look like the `Queen` and `Rook` constructors. 
Now, I'd really like to add a *method* to the function that calls an additional constructor/accessor to this function, namely the `from_dataframe` method, since popping back down into arrays in a `geopandas`-focused world requires you to unpack the `geodataframe.geometry.x, …
=> Automatically voronoi input point dataframes to Queen/Rook

libpysal/weights/weights.py
Minor change to W's silence_warnings workflow
=> minor change to W's silence_warnings workflow

CHANGELOG.md, MANIFEST.in, libpysal/__init__.py
We did not update MANIFEST.in when additional requirements files were added to the project.
=> BUG: Updating manifest for additional requirements files

CHANGELOG.md
=> REL 4.1.1 bf release

README.rst
3. [x] This pull introduces new functionality covered by
4. [x] You have [assigned a
reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests- …
=> Updated documentation error (link incorrectly specified) in README.rst 

libpysal/cg/alpha_shapes.py
The justification for this PR is:
- Addressing #199 
- ~~Adjusting docstring examples~~
- Removing extra spaces
=> fix quasi-redundant import of shapely

libpysal/io/util/shapefile.py
This PR provides minor documentation improvements in [`io.util.shapefile`](https://github.com/pysal/libpysal/blob/master/libpysal/io/util/shapefile.py) for:
* spelling
* capitalization
* grammar
=> improved docs in io.util.shapefile

libpysal/cg/standalone.py
The justification for this PR is: 
* Fixes #195 
* corrects grammar and spelling in docstring of `cg.standalone.distance_matrix`
=> updating cg.standalone.distance_matrix docs

libpysal/weights/tests/test_adjlist.py, libpysal/weights/tests/test_util.py
=> BUG:  ufunc.outer deprecated

libpysal/io/fileio.py, libpysal/io/iohandlers/wk1.py, libpysal/io/util/wkt.py, libpysal/weights/distance.py, libpysal/weights/spintW.py, libpysal/weights/util.py, libpysal/weights/weights.py
3. [N/A] This pull introduces new functionality covered by [docstrings](https://en.wikipedia.org/wiki/Docstring#Python) and [unittests](https://docs.python.org/2/library/unittest.html)? 
4. [N/A] You have [assigned a reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) and added relevant [labels](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/) <- not possible
5. [x] The justification for this PR …
=> Fix syntax errors

libpysal/cg/sphere.py
3. [x] This pull introduces new functionality covered by [docstrings](https://en.wikipedia.org/wiki/Docstring#Python) and [unittests](https://docs.python.org/2/library/unittest.html)? 
4. [N/A] You have [assigned a reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) and added relevant [labels](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/) <- not possible
5. [x] The justification for this PR …
=> DOC: Fix invalid section headings.

libpysal/examples/10740/README.md, libpysal/examples/baltim/README.md, libpysal/examples/burkitt/README.md, libpysal/examples/chicago/README.md, libpysal/examples/geodanet/README.md, libpysal/examples/juvenile/README.md, libpysal/examples/sids2/README.md, libpysal/examples/snow_maps/README.md, libpysal/examples/tokyo/README.md
1. [X] You have run tests on this submission, either by using [Travis Continuous Integration testing](https://github.com/pysal/pysal/wiki/GitHub-Standard-Operating-Procedures#automated-testing-w-travis-ci) testing or running `nosetests` on your changes?
[Proof of pass](https://github.com/jeffcsauer/libpysal/runs/532019714). However, 3.6 hangs and eventually fails as experienced [here](https://github.com/pysal/libpysal/pull/264).
2. [X] This pull request is directed to the `pysal/master` branch.
3. [X] This pull introduces new functionality covered by [docstrings](https://en.wikipedia.org/wiki/Docstring#Python) and [unittests](https://docs.python.org/2/library/unittest.html)? 
4. [X] You have [assigned a reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other- …
=> DOC: Udpdating citations, minor description editing

.github/CONTRIBUTING.md, README.rst, requirements_dev.txt
This PR:
* updates `requirements_dev.txt`
* adds `pre-commit`
* removes unneeded packages
* updates `README.rst` with links to `CONTRIBUTING.md`
* adds `black`/`pre-commit` instructions to `CONTRIBUTING.md`
=> Update CONTRIBUTING.md with pre-commit instructions

.github/workflows/release_and_publish.yml, tools/gitcount.ipynb
=> adding release_and_publish.yml

.github/PULL_REQUEST_TEMPLATE.md
=> Updating PULL_REQUEST_TEMPLATE.md

.pre-commit-config.yaml, codecov.yml
=> Add codecov.yml

libpysal/examples/remotes.py, setup.py
=> This address a move in remote datasets 

.github/workflows/release_and_publish.yml, libpysal/__init__.py, libpysal/examples/base.py
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Fix release action

environment.yml
Dependencies for examples in notebooks.
=> Adding deps for examples.

libpysal/__init__.py
=> bump to v4.3.2 for release action

README.rst, libpysal/__init__.py, setup.py
This PR corrects several issues [causing a failure](https://github.com/pysal/libpysal/runs/1715080689?check_suite_focus=true#step:11:14) at PyPI upload.
=> Correct readme.rst

README.rst, libpysal/__init__.py
This PR attempts to resolve #380
=> adjust duplicated rst link in README

environment.yml
remove duplicate `matplotlib` in `environment.yml`
=> remove dup matplotlib in environment.yml

w_workbench.ipynb
1. [ ] You have run tests on this submission locally using `pytest` on your changes. Continuous integration will be run on all PRs with [GitHub Actions](https://github.com/pysal/libpysal/blob/master/.github/workflows/unittests.yml), but it is good practice to test changes locally prior to a making a PR.
2. [ ] This pull request is directed to the `pysal/master` branch.
3. [ ] This pull introduces new functionality covered by
4. [ ] You have [assigned a …
=> Add start of workbench notebook

libpysal/cg/ops/tests/test_tabular.py, libpysal/examples/__init__.py, libpysal/examples/remotes.py
=> Do not poll remotes on init.

.github/workflows/unittests.yml
1. [ ] You have run tests on this submission locally using `pytest` on your changes. Continuous integration will be run on all PRs with [GitHub Actions](https://github.com/pysal/libpysal/blob/master/.github/workflows/unittests.yml), but it is good practice to test changes locally prior to a making a PR.
2. [ ] This pull request is directed to the `pysal/master` branch.
3. [ ] This pull introduces new functionality covered by
4. [ ] You have [assigned a …
=> update Codecov action: major version only

libpysal/weights/tests/test_util.py, libpysal/weights/util.py
3. [x] This pull introduces new functionality covered by
4. [x] You have [assigned a …
=> cast sw to csc and eliminate zeros

tools/gitcount.ipynb
=> update version import in gitcount

ci/38.yaml, ci/39.yaml, ci/travis/36-latest-conda-forge.yaml, ci/travis/37-latest-conda-forge.yaml, libpysal/examples/base.py, libpysal/examples/remotes.py, requirements.txt
Using [appdirs](https://github.com/ActiveState/appdirs) to handle local storage of examples.
=> ENH: Moving to appdirs for example storage

libpysal/weights/__init__.py, libpysal/weights/gabriel.py, libpysal/weights/tests/test_gabriel.py
This adds a revised `numba`-accelerated version of the Voronoi constructor (which avoids building the Voronoi polygons explicitly and instead opts to work directly with the Delaunay graph) and implements a Gabriel graph constructor (*edit: and a relative neighborhood constructor*) based on the new Voronoi/Delaunay constructor. The Gabriel graph is a subset of the Delaunay triangulation where the circle whose diameter is edge *ij* contains no other point *k*.
Given the fast `QHull` Delaunay constructor, we can just start from the Delaunay triangulation and remove links *ij* if *k*, some other neighbor of *i*, is within the circle whose diameter is *ij*. 
To do this, we first can say (by [Thales' Theorem](https://en.wikipedia.org/wiki/Thales%27s_theorem)) that any triangle *ijk* with a side …
=> add gabriel weights and more performant voronoi generation

.pre-commit-config.yaml, libpysal/examples/tests/test_available.py, libpysal/weights/_contW_lists.py
=> type vs. geom_type with shapely

libpysal/weights/tests/test_weights.py, libpysal/weights/weights.py
Rolling our own encoder to avoid a heavy dependency.
resolves #508
=> Remove sklearn dependency

libpysal/cg/alpha_shapes.py
Replacing pygeos with shapely 2.
=> REF: use shapely 2 instead of pygeos

libpysal/weights/tests/test_util.py, libpysal/weights/util.py
=> BUG: fix WSP2W weights casting

ci/38-minimal.yaml, libpysal/graph/_set_ops.py, libpysal/graph/_utils.py, libpysal/graph/base.py, libpysal/graph/tests/test_base.py
This is just a start, no need to merge yet. I'll continue later today a bit and then after the weekend.
=> Test graph class

libpysal/graph/_triangulation.py
This has complete working drafts of the triangulation weights.
=> Geographs _triangulation weights 

libpysal/graph/tests/test_triangulation.py
Cover clique policy for Voronoi weights
=> tests for clique policy in triangulation weights

ci/38-minimal.yaml, libpysal/graph/_parquet.py, libpysal/graph/_set_ops.py, libpysal/graph/_utils.py, libpysal/graph/base.py, libpysal/graph/tests/test_base.py, libpysal/graph/tests/test_builders.py, libpysal/graph/tests/test_triangulation.py, requirements.txt
This builds on top of @knaaptime's #555 and refactors `_adjacency` from a DataFrame to a Series with a MultiIndex. 
All seems to be good 🎉
I still want to look at performance but it is promising.
closes #555
=> adjacency as mutliindex series

libpysal/graph/_contiguity.py, libpysal/graph/_kernel.py, libpysal/graph/_set_ops.py, libpysal/graph/_utils.py, libpysal/graph/base.py, libpysal/graph/tests/test_builders.py
- revise perimeter weights
- fix kernel weirdess
- start working on set ops
I started doing set ops but got stuck on the expected logic there that would not break our sorting and sparse I/O assumptions. Will need to discuss that later today. See the comment in `intersection` in the meantime.
=> perimeter weights, fix kernel, set_ops

libpysal/graph/tests/test_contiguity.py
=> Update `test_contiguity.py` – minor typos

.github/workflows/unittests.yml
Reverts pysal/libpysal#568
xref https://github.com/codecov/codecov-action/issues/1089
=> Revert "Bump codecov/codecov-action from 3 to 4"

docs/api.rst, libpysal/graph/base.py
Adding to API reference under Experimental and fixing some formatting issues.
=> DOC: add Graph to API docs

.github/workflows/release_and_publish.yml
Follow `spaghetti` example and generate changelog using Github.
=> GHA: update release action

pyproject.toml
xref: https://github.com/pysal/libpysal/issues/562#issuecomment-1742182538
=> README is rst, not md --> update pyproject.toml

.github/workflows/unittests.yml
=> manual trigger for CI

libpysal/cg/__init__.py, libpysal/cg/ops/__init__.py, libpysal/common.py, libpysal/examples/__init__.py, libpysal/io/__init__.py, libpysal/io/iohandlers/__init__.py, libpysal/io/util/__init__.py, libpysal/weights/__init__.py, pyproject.toml
This PR kicks off #589. Should we do this:
1. piece-meal one small PR at a time; or
2. do one PR, but go incrementally with small chunks + reviews
(This process is going to be a slog... between 2k-3k fixes on first inspection)
=> begin the repo linting 

.github/workflows/unittests.yml
=> Print spatial versions in CI

libpysal/io/fileio.py
=> fix fileio regression

libpysal/io/util/tests/test_shapefile.py, libpysal/io/util/tests/test_weight_converter.py, libpysal/io/util/tests/test_wkt.py, libpysal/io/util/weight_converter.py
This PR formats and lints `io/{tests, util}/*.py` –  part 2 of $n$
=> lint & format `io/{tests, util}/*.py` part 2

libpysal/weights/gabriel.py, libpysal/weights/raster.py, libpysal/weights/set_operations.py
This PR:
* formats and lints `weights/*.py` –  part 3 of $n$
=> lint & format `weights/*.py part 3

libpysal/weights/spatial_lag.py, libpysal/weights/spintW.py, libpysal/weights/user.py
This PR:
* formats and lints `weights/*.py` –  part 4 of $n$
=> lint & format `weights/*.py part 4

libpysal/weights/util.py
This PR:
* formats and lints `weights/*.py` –  part 5 of $n$
=> lint & format `weights/*.py part 5

libpysal/graph/base.py
Added Examples section to `build_block_contiguity` docstring
=> DOC: add examples to build_block_contiguity

libpysal/examples/remotes.py, libpysal/examples/tests/test_available.py
1. [ ] You have run tests on this submission locally using `pytest` on your changes. Continuous integration will be run on all PRs with [GitHub Actions](https://github.com/pysal/libpysal/blob/master/.github/workflows/unittests.yml), but it is good practice to test changes locally prior to a making a PR.
2. [ ] This pull request is directed to the `pysal/master` branch.
3. [ ] This pull introduces new functionality covered by
4. [ ] You have [assigned a …
=> inserted chicagoSDOH as sample data

libpysal/graph/_plotting.py, libpysal/graph/tests/test_plotting.py
=> ENH: use representative_point instead of centroid in Graph plotting

.github/workflows/unittests.yml
This PR:
* adds testing against intel & apple silicon
* removes section that doesn't work
* xref https://github.com/pysal/pysal/issues/1298
=> test against intel & apple silicon

libpysal/graph/base.py
=> added examples to graph

libpysal/cg/tests/test_voronoi.py, libpysal/cg/voronoi.py
Fixes #776
~Regarging the tests for this, this does fix the case reported in the issue but I don't really want to include those files in CI. @jGaboardi thoughts?~
=> add union fallback to voronoi_frames

README.md
=> Adopting spec0
